name: Monitor Checkout Ambito

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  checkout-check:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegador Chromium
        run: npx playwright install --with-deps chromium

      - name: Ejecutar script de monitoreo
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
          WHATSAPP_APIKEY: ${{ secrets.WHATSAPP_APIKEY }}
        run: node monitor.js